import React, { useEffect, useState } from 'react';
import './AdminPanel.css';

const API_URL = process.env.REACT_APP_API_URL || '';

export default function TradeLogs() {
  const [logs, setLogs] = useState([]);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(true);

  const load = async () => {
    try {
      const res = await fetch(`${API_URL}/api/trade-logs?limit=200`);
      const json = await res.json();
      setLogs(json);
    } catch (e) {
      setError(e.message || String(e));
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    load();
    const id = setInterval(load, 5000);
    return () => clearInterval(id);
  }, []);

  if (loading) return <div className="admin-panel"><p>Loading trade logs...</p></div>;
  if (error) return <div className="admin-panel"><p style={{color:'#ef4444'}}>Error: {error}</p></div>;

  return (
    <div className="admin-panel">
      <h2>Trade Logs</h2>
      <p style={{ fontSize: 12, color: '#9ca3af' }}>Completed paper trades generated by the live trading loop.</p>
      <div style={{ overflowX: 'auto' }}>
        <table className="admin-table">
          <thead>
            <tr>
              <th>ID</th>
              <th>Time</th>
              <th>Symbol</th>
              <th>Side</th>
              <th>Qty</th>
              <th>Price</th>
              <th>Reason</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            {logs.length === 0 && (
              <tr><td colSpan={8} style={{ color: '#9ca3af' }}>No trades yet. Click Start on the Trading tab to begin.</td></tr>
            )}
            {logs.map((t) => (
              <tr key={t.id}>
                <td>{t.id}</td>
                <td>{t.created_at ? new Date(t.created_at).toLocaleString() : ''}</td>
                <td>{t.symbol}</td>
                <td style={{ color: t.side === 'BUY' ? '#22c55e' : '#ef4444' }}>{t.side}</td>
                <td>{Number(t.qty).toFixed(6)}</td>
                <td>{Number(t.price).toFixed(8)}</td>
                <td>{t.reason}</td>
                <td>{t.status}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
